# Generated by Django 3.2.7 on 2021-09-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
