# Generated by Django 3.2.7 on 2021-09-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='topic_status',
            field=models.CharField(choices=[('completed', 'completed'), ('in_progress', 'in_progress')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
